name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to AWS ECR
        env:
          AWS_ECR_REGISTRY: "767397807499.dkr.ecr.us-east-1.amazonaws.com"
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

      - name: Build the Docker image
        run: docker build -t rerassor .

      - name: Tag the Docker image
        env:
          AWS_ECR_REGISTRY: "767397807499.dkr.ecr.us-east-1.amazonaws.com"
          AWS_ECR_REPO_NAME: "rerassor"
        run: |
          IMAGE_TAG="${AWS_ECR_REGISTRY}/${AWS_ECR_REPO_NAME}:latest"
          docker tag rerassor:latest $IMAGE_TAG

      - name: Push the Docker image to AWS ECR
        env:
          AWS_ECR_REGISTRY: "767397807499.dkr.ecr.us-east-1.amazonaws.com"
          AWS_ECR_REPO_NAME: "rerassor"
        run: |
          IMAGE_TAG="${AWS_ECR_REGISTRY}/${AWS_ECR_REPO_NAME}:latest"
          docker push $IMAGE_TAG
