name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main
    paths:
      - 'client/dist/**'
      - 'server/server.js'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        env:
          NODE_ENV: production
          SSL_KEY: /etc/letsencrypt/live/rerassor.com/privkey.pem
          SSL_CERT: /etc/letsencrypt/live/rerassor.com/fullchain.pem
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP_RASSOR }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME_RASSOR  }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD_RASSOR  }}
          script: |
            pm2 kill
            rm -r RE-RASSOR-lightweight
            git clone https://github.com/colemaring/RE-RASSOR-lightweight.git
            cd RE-RASSOR-lightweight
            cd server
            npm i 
            NODE_ENV=production SSL_KEYPATH=/etc/letsencrypt/live/rerassor.com/privkey.pem SSL_CERTPATH=/etc/letsencrypt/live/rerassor.com/fullchain.pem pm2 start server.js
            docker stop rtsp-to-web && docker rm rtsp-to-web && docker run -d --name rtsp-to-web -v $(pwd)/config.json:/config/config.json -v /etc/letsencrypt/live/rerassor.com/fullchain.pem:/config/server.crt -v /etc/letsencrypt/live/rerassor.com/privkey.pem:/config/server.key -p 8083:8083 -p 8084:8084 --restart always ghcr.io/deepch/rtsptoweb:latest &
